name:  PillMenu
author:  luscarpa
current:  v1.3
category:  Interface
tags:  [menu,navigation]
docs:  http://www.luscarpa.com/development/pillmenu-simple-pill-mootools-menu/
demo:  http://www.luscarpa.com/demo/pill-menu.php
